<?php

/**
 * Implements hook_views_api().
 */
function custom_tweaks_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'custom_tweaks') . '/views',
  );
}

/**
 * Implements hook_theme().
 */
function custom_tweaks_theme() {
  return array(
    'custom_tweaks_languages_menu' => array(
  		'variables' => array(),
      'template' => 'custom-tweaks-languages-menu',
      'path' => drupal_get_path('module', 'custom_tweaks') . '/templates',
    ),
 	);
}

function custom_tweaks_render_languages_menu() {
  $items = array(
    'fr' => 'French',
    'de' => 'German',
    'it' => 'Italian',
    'pt' => 'Portugese',
    'es' => 'Spanish',
    'ar' => 'Arabic',
    'ru' => 'Russian',
    'zh-CN' => 'Chinese',
  );

  return theme('custom_tweaks_languages_menu', array('url' => url(current_path(), array('absolute' => TRUE)), 'items' => $items));
}
